### ISSUE TITLE
BertQA infer shape failure

### ISSUE THREAD

**Issue by stu1130** [awslabs/djl#151]
### Steps to reproduce
```java
String question = "When did BBC Japan start broadcasting?";
String paragraph =
    "BBC Japan was a general entertainment Channel.\n"
    + "Which operated between December 2004 and April 2006.\n"
    + "It ceased operations after its Japanese distributor folded.";

QAInput input = new QAInput(question, paragraph);
Criteria<QAInput, String> criteria =
    Criteria.builder()
    .optApplication(Application.NLP.QUESTION_ANSWER)
    .setTypes(QAInput.class, String.class)
    .optFilter("backbone", "bert")
    .optProgress(new ProgressBar())
    .build();

    try (ZooModel<QAInput, String> model = ModelZoo.loadModel(criteria)) {
        Block block = model.getBlock();
        block.getOutputShapes(null, new Shape[] {new Shape(384), new Shape(384), new Shape(1, 1)});
    }
```

```
ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Error in operator staticbertmodel0__plus0: [11:46:04] ../src/ndarray/../operator/tensor/../elemwise_op_common.h:135: Check failed: assign(&dattr, vec.at(i)): Incompatible attr in node staticbertmodel0__plus0 at 1-th input: expected [768], got [384,768]


	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1784)
	at ai.djl.mxnet.jna.JnaUtils.inferShape(JnaUtils.java:1138)
	at ai.djl.mxnet.engine.Symbol.inferShape(Symbol.java:206)
	at ai.djl.mxnet.engine.MxSymbolBlock.getParameterShape(MxSymbolBlock.java:189)
	at ai.djl.mxnet.engine.MxSymbolBlock.getOutputShapes(MxSymbolBlock.java:155)
```

**Comment by frankfliu** [comment]
Following should work:

block.getOutputShapes(null, new Shape[] {new Shape(1), new Shape(384), new Shape(384)});

**Comment by stu1130** [comment]
verified the suggested shapes works
