### ISSUE TITLE
MXNet attach gradient while trying to run inference

### ISSUE THREAD

**Issue by lanking520** [awslabs/djl#164]
## Description

In DJL 0.6.0, MXNet got the following issues while trying to run with MXNet 1.6.0.

```
java.lang.IllegalArgumentException: Unknown operator: _npi_full_like
	at ai.djl.mxnet.jna.JnaUtils.op(JnaUtils.java:121) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:305) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:323) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDArray.zerosLike(MxNDArray.java:410) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDArray.createGradient(MxNDArray.java:255) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDArray.attachGradient(MxNDArray.java:243) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxNDArray.attachGradient(MxNDArray.java:237) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.training.ParameterStore.getValue(ParameterStore.java:139) ~[api-0.6.0.jar:?]
	at ai.djl.mxnet.engine.CachedOp.forward(CachedOp.java:99) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.mxnet.engine.MxSymbolBlock.forward(MxSymbolBlock.java:145) ~[mxnet-engine-0.6.0.jar:?]
	at ai.djl.nn.Block.forward(Block.java:116) ~[api-0.6.0.jar:?]
	at ai.djl.inference.Predictor.predict(Predictor.java:117) ~[api-0.6.0.jar:?]
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:144) ~[api-0.6.0.jar:?]
	at ai.djl.inference.Predictor.predict(Predictor.java:112) ~[api-0.6.0.jar:?]
	at
```

Although the issues are caused by missing operators (1.7.0 operators), still it should not fall into this problems since user are trying to run inference with it. It can be reproduced if you try to load DJL 0.6.0 + MXNet 1.6.0.

**Comment by lanking520** [comment]
A fix has been applied https://github.com/awslabs/djl/commit/9421d875333b088259b0440dc7a7aa49be3f72e3
