### ISSUE TITLE
Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: can't alloc

### ISSUE THREAD

**Issue by SaviorD7** [awslabs/djl#166]
## Question

Hello! I clone your repo and start testing examples.

I did:
```
cd examples
gradle run -Dmain=ai.djl.examples.training.TrainMnist
```

I get:
```

 Task :examples:run
[INFO ] - Training on: cpu().
[INFO ] - Load MXNet Engine Version 1.7.0 in 0,127 ms.
Training:     21% |тЦИтЦИтЦИтЦИтЦИтЦИтЦИтЦИтЦИ                               | Accuracy: 0,87, SoftmaxCrossEntropyLoss: 0,46, speed: 867,11 items/sec[INFO ] - train P50: 29,989 ms, P90
: 41,234 ms==-> 96% EXECUTING [1m 9s]
[INFO ] - forward P50: 0,756 ms, P90: 0,978 ms
[INFO ] - training-metrics P50: 0,031 ms, P90: 0,057 ms
[INFO ] - backward P50: 1,270 ms, P90: 1,666 ms
[INFO ] - step P50: 2,050 ms, P90: 2,842 ms
Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: can't alloc

        at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1808)
        at ai.djl.mxnet.jna.JnaUtils.waitToRead(JnaUtils.java:459)
        at ai.djl.mxnet.engine.MxNDArray.close(MxNDArray.java:1549)
        at ai.djl.mxnet.engine.MxNDArrayIndexer.get(MxNDArrayIndexer.java:52)
        at ai.djl.ndarray.index.NDArrayIndexer.get(NDArrayIndexer.java:73)
        at ai.djl.ndarray.NDArray.get(NDArray.java:498)
        at ai.djl.ndarray.NDArray.get(NDArray.java:522)
        at ai.djl.training.dataset.ArrayDataset.get(ArrayDataset.java:83)
        at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:166)
        at ai.djl.training.dataset.DataIterable.next(DataIterable.java:142)
        at ai.djl.training.dataset.DataIterable.next(DataIterable.java:41)
        at ai.djl.training.EasyTrain.fit(EasyTrain.java:44)
        at ai.djl.examples.training.TrainMnist.runExample(TrainMnist.java:86)
        at ai.djl.examples.training.TrainMnist.main(TrainMnist.java:50)
        Suppressed: java.lang.NullPointerException
                at ai.djl.examples.training.TrainMnist.lambda$setupTrainingConfig$0(TrainMnist.java:100)
                at ai.djl.training.listener.CheckpointsTrainingListener.saveModel(CheckpointsTrainingListener.java:131)
                at ai.djl.training.listener.CheckpointsTrainingListener.onTrainingEnd(CheckpointsTrainingListener.java:89)
                at ai.djl.training.Trainer.lambda$close$2(Trainer.java:309)
                at java.util.ArrayList.forEach(ArrayList.java:1259)
                at ai.djl.training.Trainer.notifyListeners(Trainer.java:263)
                at ai.djl.training.Trainer.close(Trainer.java:309)
                at ai.djl.examples.training.TrainMnist.runExample(TrainMnist.java:89)
                ... 1 more

> Task :examples:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:run'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_261\bin\java.exe'' finished with non-zero exit value 1

```

Win 10. 
What it could be ?

**Comment by frankfliu** [comment]
How much physical memory do you have?

Deep learning training job usually requires quire large memory. You need at least 15G of RAM to run this example.

**Comment by SaviorD7** [comment]
> How much physical memory do you have?
> 
> Deep learning training job usually requires quire large memory. You need at least 15G of RAM to run this example.

About 8G.

It strange cause I tried MNIST at  some other platforms and it go well. 
I had about 6,5 GB  and it just going so long, but never failed..

Okay. Thank you!
