### ISSUE TITLE
Training Obj. Detection with multiple classes and bounding boxes

### ISSUE THREAD

**Issue by androuino** [awslabs/djl#186]
## Question
Hi, great framework btw.

My question is... Say I have an **_index.file_** which has a data like below:
```
{"img_name0.jpg": [[...], [...], [...]], "img_name1.jpg": [[...], [...], [...]]}
```
So meaning I have a single image with 3 classes and multiple bounding boxes annotated. I would like to ask if my approach in getting the dataset is correct?
```
        usagePath = root.resolve(usagePath);
        Path indexFile = usagePath.resolve("index.file");
        try (Reader reader = Files.newBufferedReader(indexFile)) {
            Type mapType = new TypeToken<Map<String, List<String[]>>>() {}.getType();
            Map<String, List<String[]>> metadata = JsonUtils.GSON.fromJson(reader, mapType);
            for (Map.Entry<String, List<String[]>> entry : metadata.entrySet()) {
                for (String[] item : entry.getValue()) {
                    String imgName = entry.getKey();
                    float[] labelArray = new float[5];
                    // Class label
                    labelArray[0] = Float.parseFloat(item[0]);

                    // Bounding box labels
                    labelArray[1] = Float.parseFloat(item[1]);
                    labelArray[2] = Float.parseFloat(item[2]);
                    labelArray[3] = Float.parseFloat(item[3]);
                    labelArray[4] = Float.parseFloat(item[4]);
                    imagePaths.add(usagePath.resolve(imgName));
                    labels.add(labelArray);
                }
            }
        }
        prepared = true;
```
When I started the training with the class I have written to train my custom dataset. I am getting this error:
```
Exception in thread "main" java.lang.IllegalStateException: Data loading failed
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:145)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:41)
	at ai.djl.training.EasyTrain.fit(EasyTrain.java:44)
	at ai.djl.examples.training.TrainCustomModel.runTraining(TrainCustomModel.java:75)
	at ai.djl.examples.training.TrainCustomModel.main(TrainCustomModel.java:56)
	Suppressed: java.lang.NullPointerException
		at ai.djl.examples.training.TrainCustomModel.lambda$setUpTrainingConfig$0(TrainCustomModel.java:128)
		at ai.djl.training.listener.CheckpointsTrainingListener.saveModel(CheckpointsTrainingListener.java:131)
		at ai.djl.training.listener.CheckpointsTrainingListener.onTrainingEnd(CheckpointsTrainingListener.java:89)
		at ai.djl.training.Trainer.lambda$close$2(Trainer.java:309)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at ai.djl.training.Trainer.notifyListeners(Trainer.java:263)
		at ai.djl.training.Trainer.close(Trainer.java:309)
		at ai.djl.examples.training.TrainCustomModel.runTraining(TrainCustomModel.java:69)
		... 1 more
Caused by: javax.imageio.IIOException: Can't read input file!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1308)
	at ai.djl.modality.cv.BufferedImageFactory.fromFile(BufferedImageFactory.java:55)
	at ai.djl.examples.training.CustomObjectDetection.get(CustomObjectDetection.java:76)
	at ai.djl.training.dataset.DataIterable.fetch(DataIterable.java:166)
	at ai.djl.training.dataset.DataIterable.next(DataIterable.java:142)
	... 4 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':examples:TrainCustomModel.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-11.0.3.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```
I hope someone could help me fix the error I am getting. Thank you in advance.

**Comment by androuino** [comment]
Nevermind, I solved it already.

**Comment by zachgk** [comment]
@androuino Do you mind sharing how you solved this for those with similar problems who find this issue?

**Comment by androuino** [comment]
Sure but the problem that I have was a silly mistake because instead of putting a .jpg in the index.file, I am putting .txt that's why I have the error that it can't read the input file. The Json file should like like this:
{"image.jpg":[...], ...}
