### ISSUE TITLE
Running the examples in their own project (maven)

### ISSUE THREAD

**Issue by salamanders** [awslabs/djl#19]
## Description
Unclear which dependencies are required to run the examples, because the examples are hosted in the same module.

### Expected Behavior
Example pom.xml that allows an example to run.

### Error Message
```
Exception in thread "main" java.util.ServiceConfigurationError: ai.djl.engine.EngineProvider: Provider ai.djl.mxnet.engine.MxEngineProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at ai.djl.engine.Engine.initEngine(Engine.java:47)
	at ai.djl.engine.Engine.<clinit>(Engine.java:42)
	at ai.djl.Model.newInstance(Model.java:69)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:96)
	at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:85)
	at ai.djl.repository.zoo.ModelLoader.loadModel(ModelLoader.java:84)
	at org.example.HelloKt.predictAnswer(Hello.kt:48)
	at org.example.HelloKt.main(Hello.kt:72)
	at org.example.HelloKt.main(Hello.kt)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'mxnet':
dlopen(libmxnet.dylib, 9): image not found
dlopen(libmxnet.dylib, 9): image not found
Native library (darwin/libmxnet.dylib) not found in resource path (/Users/MYNAME/Desktop/workspace/untitled/target/classes:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.61/kotlin-stdlib-jdk8-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.61/kotlin-stdlib-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.61/kotlin-stdlib-common-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.61/kotlin-stdlib-jdk7-1.3.61.jar:/Users/MYNAME/.m2/repository/ai/djl/api/0.2.1/api-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/basicdataset/0.2.1/basicdataset-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/repository/0.2.1/repository-0.2.1.jar:/Users/MYNAME/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/MYNAME/.m2/repository/ai/djl/model-zoo/0.2.1/model-zoo-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/mxnet/mxnet-model-zoo/0.2.1/mxnet-model-zoo-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/mxnet/mxnet-engine/0.2.1/mxnet-engine-0.2.1.jar:/Users/MYNAME/.m2/repository/net/java/dev/jna/jna/5.3.0/jna-5.3.0.jar:/Users/MYNAME/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/MYNAME/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:80)
	at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:68)
	at ai.djl.mxnet.engine.MxEngine.<init>(MxEngine.java:36)
	at ai.djl.mxnet.engine.MxEngineProvider.<clinit>(MxEngineProvider.java:21)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 11 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libmxnet.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 24 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libmxnet.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 24 more
	Suppressed: java.io.IOException: Native library (darwin/libmxnet.dylib) not found in resource path (/Users/MYNAME/Desktop/workspace/untitled/target/classes:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.61/kotlin-stdlib-jdk8-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.61/kotlin-stdlib-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.61/kotlin-stdlib-common-1.3.61.jar:/Users/MYNAME/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/MYNAME/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.3.61/kotlin-stdlib-jdk7-1.3.61.jar:/Users/MYNAME/.m2/repository/ai/djl/api/0.2.1/api-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/basicdataset/0.2.1/basicdataset-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/repository/0.2.1/repository-0.2.1.jar:/Users/MYNAME/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar:/Users/MYNAME/.m2/repository/ai/djl/model-zoo/0.2.1/model-zoo-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/mxnet/mxnet-model-zoo/0.2.1/mxnet-model-zoo-0.2.1.jar:/Users/MYNAME/.m2/repository/ai/djl/mxnet/mxnet-engine/0.2.1/mxnet-engine-0.2.1.jar:/Users/MYNAME/.m2/repository/net/java/dev/jna/jna/5.3.0/jna-5.3.0.jar:/Users/MYNAME/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/MYNAME/.m2/repository/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 24 more
```

## How to Reproduce?
```kotlin
fun main() {
    val paragraph = ("""BBC Japan was a general entertainment Channel.
Which operated between December 2004 and April 2006.
It ceased operations after its Japanese distributor folded.""")
    val criteria = mapOf(
        "backbone" to "bert",
        "dataset" to "book_corpus_wiki_en_uncased"
    )
    arrayOf(
        "When did BBC Japan start broadcasting?",
        "When did BBC Japan stop broadcasting?"
    ).forEach { question ->
        val input = QAInput(question, paragraph, 384)
        println("Paragraph: ${input.paragraph}")
        println("Question: ${input.question}")
        MxModelZoo.BERT_QA.loadModel(criteria, ProgressBar()).use { model ->
            model.newPredictor().use { predictor ->
                println("Answer: ${predictor.predict(input)}")
            }
        }
    }
}
```

### Steps to reproduce
pom.xml with

```

        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>basicdataset</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>model-zoo</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-engine</artifactId>
            <version>0.2.1</version>
        </dependency>

        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-cu92mkl</artifactId>
            <version>1.6.0-b</version>
            <classifier>macosx-x86_64-gpu</classifier>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-cu101mkl</artifactId>
            <version>1.6.0-b</version>
            <classifier>macosx-x86_64-gpu</classifier>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-mkl</artifactId>
            <version>1.6.0-b</version>
            <classifier>macosx-x86_64-gpu</classifier>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.30</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.30</version>
        </dependency>

```

## What have you tried to solve it?
It ran successfully from the checkout of this project.  I'm trying to get it to run using released libs.

I tried various values in the `<classifier>macosx-x86_64-gpu</classifier>` 

## Environment Info
Please provide the following information:

* Operating System: OSX
* Hardware(Machine) Info: Macbook pro
* CUDA version(if available): ?
* Deep Java Library version: ?
* MXNet version: ?

**Comment by salamanders** [comment]
Self-contained example in https://github.com/salamanders/superdeep

**Comment by frankfliu** [comment]
@salamanders 
osx doesn't have GPU support the classifier should be: <classifier>osx-x86_64</classifier>

**Comment by salamanders** [comment]
Whohoo, that did it, thank you!

For any future readers, my pom.xml had:

```xml
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-model-zoo</artifactId>
            <version>0.2.1</version>
        </dependency>
        <dependency>
            <groupId>ai.djl.mxnet</groupId>
            <artifactId>mxnet-native-mkl</artifactId>
            <version>1.6.0-b</version>
            <classifier>osx-x86_64</classifier>
        </dependency>
```

**Comment by salamanders** [comment]
... so should I (ever) include mxnet-native-cu101mkl or mxnet-native-cu92mkl?

**Comment by zachgk** [comment]
You might. Each of the `mxnet-native-*` dependencies represent a different way of building the MXNet engine. For OSX, we only distribute the build with Intel MKL Library enabled (`-mkl`). For linux, we have more builds including builds with GPU support (this is your `-cu101mkl` and `-cu92mkl`). You can look at https://github.com/awslabs/djl/blob/master/mxnet/mxnet-engine/README.md for a list of the various builds that we distribute for each platform.

**Comment by frankfliu** [comment]
@salamanders 
macOS is official os name since 10.12, OSX is legacy name.

**Comment by salamanders** [comment]
Sure!  I'm happy with either.
I meant more that it says "following two options" but there is only one option.

**Comment by frankfliu** [comment]
@salamanders 
Thanks for clarify, I will submit a fix to address this.
