### ISSUE TITLE
Way  for proper Integer array indexing?

### ISSUE THREAD

**Issue by HuaMuLanChina** [awslabs/djl#248]
## Question
In numpy:
```
>>> array = np.ones((5,2))
>>> sel = np.array([1,2,4])
>>> array[sel].shape
(3, 2)
```
what i've tried:
```
NDArray array = manager.ones(new Shape(5,2));
long[] d = {1,2,4};
NDArray sel = manager.create(d);
array.get(sel)//error
```

**Comment by lanking520** [comment]
There is a way, try to do following the javadoc: https://javadoc.io/doc/ai.djl/api/latest/ai/djl/ndarray/index/NDIndex.html

```java
NDIndex index = new NDIndex().addIndices(0) // pick first dim
                                                      .addPickDim(sel);
array.get(sel);
```

**Comment by HuaMuLanChina** [comment]
```
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDManager;
import ai.djl.ndarray.types.Shape;
import ai.djl.ndarray.index.NDIndex;

NDManager manager = NDManager.newBaseManager();
NDArray array = manager.arange(10).reshape(-1,2);
long[] d = {1,2,4};
NDArray sel = manager.create(d);
NDIndex index = new NDIndex().addIndices(0).addPickDim(sel);
array.get(index);
```
can't pass block runner.

```
jdk.jshell.EvalException: get() currently supports all, fixed, and slices indices
	at ai.djl.ndarray.index.NDArrayIndexer.get(NDArrayIndexer.java:75)
	at ai.djl.ndarray.NDArray.get(NDArray.java:498)
	at .(#10:1)
```

**Comment by zachgk** [comment]
We don't support this right now.

For clarification, there are two types of indexing with numeric indices: [pick](https://mxnet.apache.org/versions/1.7.0/api/python/docs/api/symbol/symbol.html#mxnet.symbol.pick) and [gather](https://mxnet.apache.org/versions/1.7.0/api/python/docs/api/symbol/symbol.html#mxnet.symbol.gather_nd). We have support for pick, but need to add gather to support this.

**Comment by ManuLasker** [comment]
@HuaMuLanChina Hello, what you can do and it functions for me with the pytorch engine is:
```
NDManager manager = NDManager.newBaseManager();
NDArray array = manager.arange(10).reshape(-1,2);
long[] d = {1,2,4};
NDArray sel = manager.create(d).repeat(2).reshape(-1, 2);
NDIndex index = new NDIndex().addPickDim(sel);
array.get(index);
```
The results are:

```
ND: (3, 2) cpu() int32
[[ 2,  3],
 [ 4,  5],
 [ 8,  9],
]
```
The same results for numpy python:
```
array = np.arange(10).reshape(-1,2)
sel = np.array([1,2,4])
array[sel]
array([[2, 3],
       [4, 5],
       [8, 9]])
```
Hope this can help you :D

**Comment by HuaMuLanChina** [comment]
'repeat' works .
