### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by hmf** [awslabs/djl#440]
## Description
The code example found [here](https://docs.djl.ai/model-zoo/index.html#how-to-find-a-pre-trained-model-in-the-model-zoo) is incorrect. The class `Classification.class`should be `Classifications.class`. 

### Expected Behavior

Expected to copy the example, execute it and get a model loaded. 

### Error Message
```
09:24:00.447 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.basicmodelzoo.BasicZooProvider
09:24:00.447 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.mxnet.zoo.MxZooProvider
09:24:00.448 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.tensorflow.zoo.TfZooProvider
09:24:00.448 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Searching model in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
09:24:00.448 [main] DEBUG ai.djl.repository.zoo.ModelZoo - No model zoo found in zoo provider: ai.djl.repository.zoo.DefaultZooProvider
09:24:00.448 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.zoo:resnet
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:resnet
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.zoo:mlp
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:mlp
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.zoo:ssd
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.mxnet:ssd
09:24:00.449 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.mxnet:yolo
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:alexnet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:alexnet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:darknet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:darknet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:densenet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:densenet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:googlenet
09:24:00.450 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:googlenet
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:inceptionv3
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:inceptionv3
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:mlp
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:mlp
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:mobilenet
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:mobilenet
09:24:00.451 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnest
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:resnest
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnet
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:resnet
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:resnext
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:resnext
09:24:00.452 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:senet
09:24:00.453 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:senet
09:24:00.453 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:se_resnext
09:24:00.453 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:se_resnext
09:24:00.453 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:squeezenet
09:24:00.453 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:squeezenet
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:vgg
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:vgg
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.mxnet:xception
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:xception
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/pose_estimation ai.djl.mxnet:simple_pose
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/instance_segmentation ai.djl.mxnet:mask_rcnn
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/action_recognition ai.djl.mxnet:action_recognition
09:24:00.454 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: nlp/question_answer ai.djl.mxnet:bertqa
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: nlp/word_embedding ai.djl.mxnet:glove
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.tensorflow:resnet
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:resnet
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/image_classification ai.djl.tensorflow:mobilenet
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - input/output type found for ModelLoader: CV.IMAGE_CLASSIFICATION null:mobilenet
09:24:00.455 [main] DEBUG ai.djl.repository.zoo.ModelZoo - Checking ModelLoader: cv/object_detection ai.djl.tensorflow:ssd
Exception in thread "main" ai.djl.repository.zoo.ModelNotFoundException: No matching model with specified Input/Output type found.
	at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:173)
	at examples.djl.LoadModelZoo$.main(LoadModelZoo.scala:233)
	at examples.djl.LoadModelZoo.main(LoadModelZoo.scala)

``` 

## How to Reproduce?
Run the code example as is.

### Steps to reproduce

1. Copy & paste the example
2. Adapted to Scala (see code below)
3. Execute

```scala
    val criteria = Criteria.builder()
     .optApplication(Application.CV.IMAGE_CLASSIFICATION)
      .setTypes(classOf[Image], classOf[Classification])
      .optFilter("layers", "50")
      .optFilter("flavor", "v1")
      .optFilter("dataset", "cifar10")
      .build()

    val ssd = ModelZoo.loadModel(criteria)
```

## What have you tried to solve it?

To solve it, the class type must be changed as follows:

```scala
    val criteria: Criteria[Image, Classifications] = Criteria.builder()
      .optApplication(Application.CV.IMAGE_CLASSIFICATION)
      .setTypes(classOf[Image], classOf[Classifications])
      .optFilter("layers", "50")
      .optFilter("flavor", "v1")
      .optFilter("dataset", "cifar10")
      .build()

    val ssd: ZooModel[Image, Classifications] = ModelZoo.loadModel(criteria)
```

## Environment Info

I execute this in a Scala project (JDK11,  Scala 3 (M2), Mill build tool, Linux)

**Comment by lanking520** [comment]
@hmf Please feel free to raise a PR to fix it

**Comment by stu1130** [comment]
the doc has been fixed
