### ISSUE TITLE
How to deploy RNN model from pytorch

### ISSUE THREAD

**Issue by jinlong-hao** [awslabs/djl#480]
## Question
I'm a beginner of pytorch, and I trainned my first NLP-RNN model with the tutorial of pytorch（https://pytorch.org/tutorials/intermediate/char_rnn_classification_tutorial）

~~~python
import torch.nn as nn

class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()

        self.hidden_size = hidden_size

        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim=1)

    def forward(self, input, hidden):
        combined = torch.cat((input, hidden), 1)
        hidden = self.i2h(combined)
        output = self.i2o(combined)
        output = self.softmax(output)
        return output, hidden

    def initHidden(self):
        return torch.zeros(1, self.hidden_size)

n_hidden = 128
rnn = RNN(n_letters, n_hidden, n_categories)

...

example = torch.rand(10, 1, 57)
trace_script_model = torch.jit.trace(rnn, (example, rnn.initHidden()))
trace_script_model.save('./output/char-rnn.pt')
~~~

When I load data from in djl, and I got the error: 
the model expect input and hidden parameter.

Then I change the model as below:
~~~python
import torch.nn as nn
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNN, self).__init__()
        self.hidden_size = hidden_size
        self.i2h = nn.Linear(input_size + hidden_size, hidden_size)
        self.i2o = nn.Linear(input_size + hidden_size, output_size)
        self.softmax = nn.LogSoftmax(dim = 1)
        
        
    def forward(self, input):
        hidden = self.initHidden()
        for i in range(input.size()[0]):
            combined = torch.cat((input[i], hidden), 1)
            hidden = self.i2h(combined)
            output = self.i2o(combined)
            output = self.softmax(output)
        return output
    
    def initHidden(self):
        return torch.zeros(1, self.hidden_size)
    
n_hidden = 128
rnn = RNN(n_letters, n_hidden, n_category)
example = torch.rand(10, 1, 57)
trace_script_model = torch.jit.trace(rnn, example)
trace_script_model.save('./output/char-rnn.pt')
~~~

~~~java
        Criteria<NDList, NDList> criteria =
                Criteria.builder()
                        .setTypes(NDList.class, NDList.class)
                        .optModelUrls("file:///E:/01-python/02-pytorch/output/char-rnn")
                        .optTranslator(new NoopTranslator())
                        .build();

        ZooModel<NDList, NDList> model = ModelZoo.loadModel(criteria);
        Predictor<NDList, NDList> predictor = model.newPredictor();

        Shape shape = new Shape(10,  1, 57);

        NDArray ndArray = NDManager.newBaseManager().create(new int[]
                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0 ,

                        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0,

                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0  }, shape);
        NDList ndList = new NDList();
        ndList.add(ndArray);
        predictor.predict(ndList.toDevice(Device.cpu(), true));
~~~

When I call predictor to predict the model, I got the Exception below:
~~~
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/___torch_mangle_8.py", line 16, in forward
    input0 = torch.cat([torch.select(input, 0, 0), hidden], 1)
    _3 = (_2).forward(input0, )
    _4 = (_0).forward((_1).forward(input0, ), )
                       ~~~~~~~~~~~ <--- HERE
    input1 = torch.cat([torch.select(input, 0, 1), _3], 1)
    _5 = (_2).forward1(input1, )
  File "code/__torch__/___torch_mangle_8.py", line 15, in forward
    hidden = torch.zeros([1, 128], dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
    input0 = torch.cat([torch.select(input, 0, 0), hidden], 1)
    _3 = (_2).forward(input0, )
          ~~~~~~~~~~~ <--- HERE
    _4 = (_0).forward((_1).forward(input0, ), )
    input1 = torch.cat([torch.select(input, 0, 1), _3], 1)
  File "code/__torch__/___torch_mangle_8.py", line 14, in forward
    _2 = self.i2h
    hidden = torch.zeros([1, 128], dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False)
    input0 = torch.cat([torch.select(input, 0, 0), hidden], 1)
             ~~~~~~~~~ <--- HERE
    _3 = (_2).forward(input0, )
    _4 = (_0).forward((_1).forward(input0, ), )

Traceback of TorchScript, original code (most recent call last):
<ipython-input-42-bee303b6380c>(14): forward
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\torch\nn\modules\module.py(704): _slow_forward
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\torch\nn\modules\module.py(720): _call_impl
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\torch\jit\__init__.py(1109): trace_module
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\torch\jit\__init__.py(955): trace
<ipython-input-54-7c31d9bd5822>(2): <module>
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\interactiveshell.py(3417): run_code
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\interactiveshell.py(3337): run_ast_nodes
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\interactiveshell.py(3146): run_cell_async
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\async_helpers.py(68): _pseudo_sync_runner
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\interactiveshell.py(2922): _run_cell
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\IPython\core\interactiveshell.py(2877): run_cell
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\zmqshell.py(536): run_cell
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\ipkernel.py(306): do_execute
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\gen.py(209): wrapper
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\kernelbase.py(545): execute_request
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\gen.py(209): wrapper
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\kernelbase.py(268): dispatch_shell
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\gen.py(209): wrapper
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\kernelbase.py(365): process_one
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\gen.py(748): run
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\gen.py(787): inner
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\ioloop.py(743): _run_callback
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\ioloop.py(690): <lambda>
c:\users\lenovo\appdata\local\programs\python\python37\lib\asyncio\events.py(88): _run
c:\users\lenovo\appdata\local\programs\python\python37\lib\asyncio\base_events.py(1786): _run_once
c:\users\lenovo\appdata\local\programs\python\python37\lib\asyncio\base_events.py(541): run_forever
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\tornado\platform\asyncio.py(149): start
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel\kernelapp.py(612): start
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\traitlets\config\application.py(837): launch_instance
c:\users\lenovo\.virtualenvs\02-pytorch-vqj5pwve\lib\site-packages\ipykernel_launcher.py(16): <module>
c:\users\lenovo\appdata\local\programs\python\python37\lib\runpy.py(85): _run_code
c:\users\lenovo\appdata\local\programs\python\python37\lib\runpy.py(193): _run_module_as_main
RuntimeError: Tensors must have same number of dimensions: got 3 and 2

	at ai.djl.pytorch.jni.PyTorchLibrary.moduleForward(Native Method)
	at ai.djl.pytorch.jni.IValueUtils.forward(IValueUtils.java:211)
	at ai.djl.pytorch.engine.PtSymbolBlock.forward(PtSymbolBlock.java:110)
	at ai.djl.nn.Block.forward(Block.java:117)
	at ai.djl.inference.Predictor.predict(Predictor.java:117)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:157)
	at ai.djl.inference.Predictor.predict(Predictor.java:112)
	at cn.eppdev.test.djl.pytorch.AppMain.testCharRnn(AppMain.java:110)
	at cn.eppdev.test.djl.pytorch.AppMain.main(AppMain.java:41)
~~~

**Comment by lanking520** [comment]
It looks like your input data type is not correct. Try with 
NDManager.ones(new Shape(10,1,57), DataType.Float32);

**Comment by lanking520** [comment]
Also NoopTranslator should have no batchifier by default right @frankfliu

**Comment by frankfliu** [comment]
> Also NoopTranslator should have no batchifier by default right @frankfliu

NoopTranslator has no batchifier since 0.9.0, it was using stack batchifier before 0.8.0

**Comment by lanking520** [comment]
> > Also NoopTranslator should have no batchifier by default right @frankfliu
> 
> 
> 
> NoopTranslator has no batchifier since 0.9.0, it was using stack batchifier before 0.8.0

So if @jinlong-hao you are using 0.8.0, the input will probably have 4 dimensions even if you try to feed 3-dim inputs

**Comment by jinlong-hao** [comment]
@lanking520 @frankfliu It works all right when I upgrade djl to 0.9.0, but I can not input the data with dynamic length. As the example above,  the size of the ndarray must be [10, 1, 57] as the sample data in torch script.

is there any way that I can input the ndarray with the others size, such as [9, 1, 57]?

**Comment by lanking520** [comment]
> @lanking520 @frankfliu It works all right when I upgrade djl to 0.9.0, but I can not input the data with dynamic length. As the example above,  the size of the ndarray must be [10, 1, 57] as the sample data in torch script.
> 
> 
> 
> is there any way that I can input the ndarray with the others size, such as [9, 1, 57]?  

This issue seemed introduced by the model itself. Usually TorchScript does not set the limitation of the batch size. You can try with PyTorch Python first to see if you can provide dynamic lengths. DJL does not set limitation on that.

**Comment by jinlong-hao** [comment]
@lanking520 Yes, It's the problem of torchscript!
with the basic model "rnn", I can provide dynamic length. but when I load model from the torch script,  the input size must be [10, 1, 57]
