### ISSUE TITLE
NDIndex does not support -1

### ISSUE THREAD

**Issue by roywei** [awslabs/djl#76]
There is a bug when trying to get "-1" from NDIndex, can be reproduced by change the following test:

```
    @Test
    public void testGet() {
        try (NDManager manager = NDManager.newBaseManager()) {
            NDArray original = manager.create(new float[] {1f, 2f, 3f, 4f}, new Shape(2, 2));
            Assert.assertEquals(original.get(new NDIndex()), original);
            original.get("-1");
```

**Work around:
use `get(":-1")` works**

strack trace:

```
    [ERROR] - Test ai.djl.integration.tests.ndarray.NDArrayOtherOpTest.testGet FAILED
    [ERROR] -
    ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: dshape[axes[i]] == 1 (0 vs. 1) : cannot select an axis to squeeze out which has size=0 not equal to one
    Stack trace:
      File "../src/operator/numpy/np_matrix_op.cc", line 438

        at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1788) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.jna.JnaUtils.imperativeInvoke(JnaUtils.java:500) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:82) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:66) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:319) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:337) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.engine.MxNDArray.squeeze(MxNDArray.java:1200) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.mxnet.engine.MxNDArray.get(MxNDArray.java:431) ~[mxnet-engine-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.ndarray.NDArray.get(NDArray.java:500) ~[api-0.6.0-SNAPSHOT.jar:?]
        at ai.djl.integration.tests.ndarray.NDArrayOtherOpTest.testGet(NDArrayOtherOpTest.java:33) ~[main/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at ai.djl.integration.IntegrationTest$TestClass.runTest(IntegrationTest.java:350) [main/:?]
        at ai.djl.integration.IntegrationTest.runTests(IntegrationTest.java:111) [main/:?]
        at ai.djl.integration.IntegrationTest.runTests(IntegrationTest.java:80) [main/:?]
        at ai.djl.integration.IntegrationTests.runIntegrationTests(IntegrationTests.java:23) [test/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) [testng-6.8.1.jar:?]
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.1.jar:?]
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.1.jar:?]
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.1.jar:?]
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.1.jar:?]
        at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.1.jar:?]
        at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:334) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunner.run(SuiteRunner.java:240) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.1.jar:?]
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.1.jar:?]
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.1.jar:?]
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.1.jar:?]
        at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.1.jar:?]
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141) [gradle-testing-jvm-6.4.1.jar:6.4.1]
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90) [gradle-testing-jvm-6.4.1.jar:6.4.1]
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61) [gradle-testing-base-6.4.1.jar:6.4.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94) [gradle-messaging-6.4.1.jar:6.4.1]
        at com.sun.proxy.$Proxy2.stop(Unknown Source) [?:?]
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132) [gradle-testing-base-6.4.1.jar:6.4.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_231]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:413) [gradle-messaging-6.4.1.jar:6.4.1]
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64) [gradle-base-services-6.4.1.jar:6.4.1]
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48) [gradle-base-services-6.4.1.jar:6.4.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_231]
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56) [gradle-base-services-6.4.1.jar:6.4.1]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by zachgk** [comment]
Fixed in https://github.com/awslabs/djl/commit/637f24afe9b68a6aa33179e3ebc758398383b098
