### ISSUE TITLE
Running mxnet demo on arm64, unsatisfied link

### ISSUE THREAD

**Issue by DjToMeK27** [awslabs/djl#760]
Hello

I have tried running 
https://github.com/aws-samples/djl-demo/tree/master/android/mxnet-android
demo .

I have a problem on arm64 devices.  I tried running it on my Pixel 3a and Samsung Galaxy
I have downloaded arm64-v8a_native.zip file an copied it into
jniLibs/arm64-v8a

https://i.imgur.com/qSKOrGX.png

but I get an error 
Native library (android-aarch64/libmxnet.so) not found in resource path (.)

I think the problem is with running com.sun.jna.NativeLibrary.loadLibrary, which trys to load android-aarch64 arhitecture on Android device
I tried running x86 and x86_64 and this both works normally on emulator

**Comment by stu1130** [comment]
Hi @DjToMeK27 I think 4 common ABIs are [`x86`, `x86_64`, `armeabi-v7a` and `arm64-v8a`](https://developer.android.com/ndk/guides/abis). It should cover 95% coverage. You don't need android-aarch64/libmxnet.so and just use `arm64-v8a` for 64 bit arch

**Comment by DjToMeK27** [comment]
@stu1130  hello.
Yes I have arm64-v8a also added to my project but it does not seem to work. As said I have only problems with this type of ABI, others work ok. Will check if I misses something, but it does look like the library is looking in the wrong directory

**Comment by frankfliu** [comment]
@DjToMeK27 
On Android, DJL relay on android system to set to proper java.library.path.
com.sun.jna.Native.load() function underneath is calling System.loadLibrary(), It must be some mismatch at android layer.

**Comment by stu1130** [comment]
> @stu1130 hello.
> Yes I have arm64-v8a also added to my project but it does not seem to work. 

What error did you get? If it is `not found`, it should be config problem on android layer as @frankfliu mentioned. If it is UnsatisfiedLink error in native library, it probably due to broken native library. We can try to rebuild it from source

**Comment by DjToMeK27** [comment]
As said, native library not found

This is whole message

`2021-03-22 08:58:32.086 19596-19660/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: ai.djl.examples.mxnet_android_template, PID: 19596
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: ai.djl.engine.EngineException: No deep learning engine found.
    Please refer to https://github.com/awslabs/djl/blob/master/docs/development/troubleshooting.md for more details.
        at ai.djl.engine.Engine.getInstance(Engine.java:120)
        at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:115)
        at ai.djl.repository.zoo.ModelZoo.loadModel(ModelZoo.java:190)
        at ai.djl.examples.MainActivity$LoadModel.doInBackground(MainActivity.java:73)
        at ai.djl.examples.MainActivity$LoadModel.doInBackground(MainActivity.java:55)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        	... 4 more
     Caused by: ai.djl.engine.EngineException: Failed to load MXNet native library
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:71)
        at ai.djl.mxnet.engine.MxEngineProvider.getEngine(MxEngineProvider.java:27)
        at ai.djl.engine.Engine.initEngine(Engine.java:62)
        at ai.djl.engine.Engine.<clinit>(Engine.java:52)
        at ai.djl.engine.Engine.getInstance(Engine.java:117)
        	... 10 more
     Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'mxnet':
    dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
    dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
    dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
    Native library (android-aarch64/libmxnet.so) not found in resource path (.)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
        at com.sun.jna.Library$Handler.<init>(Library.java:192)
        at com.sun.jna.Native.load(Native.java:596)
        at ai.djl.mxnet.jna.LibUtils.loadLibrary(LibUtils.java:72)
        at ai.djl.mxnet.jna.JnaUtils.<clinit>(JnaUtils.java:69)
        at ai.djl.mxnet.jna.JnaUtils.getAllOpNames(JnaUtils.java:88)
        at ai.djl.mxnet.engine.MxEngine.newInstance(MxEngine.java:49)
        	... 14 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
        		... 21 more
    	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
        at com.sun.jna.Native.open(Native Method)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
        		... 21 more
2021-03-22 08:58:32.087 19596-19660/? E/AndroidRuntime: 	Suppressed: java.lang.UnsatisfiedLinkError: dlopen failed: library "libopenblas.so" not found: needed by /data/app/~~PMFaDTL5_sXMoTOS8ju7Tw==/ai.djl.examples.mxnet_android_template-xQ2vqDuBtyB5XvOIuB_5-w==/base.apk!/lib/arm64-v8a/libmxnet.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:218)
        		... 21 more
    	Suppressed: java.io.IOException: Native library (android-aarch64/libmxnet.so) not found in resource path (.)
        at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
        		... 21 more`

**Comment by stu1130** [comment]
@DjToMeK27 Thanks will try to rebuild libmxnet.so

**Comment by stu1130** [comment]
@DjToMeK27 please try again. I re-uploaded the new arm64-v8a libmxnet

**Comment by DjToMeK27** [comment]
@stu1130 it works now! Thank you! <3
