### ISSUE TITLE
Reshape exception during NDArray.set() 

### ISSUE THREAD

**Issue by waicool20** [awslabs/djl#80]
## Description
DJL seems to complain when trying to set multiple elements via function when using NDIndex slicing.
I was expecting the example below to apply sigmoid function to elements 2-3 in each array 
Setting just a number works though: 
```
        array.set(new NDIndex(":, 2:"), 2);
```

### Error Message
```
ND: (2, 4) gpu(0) float32
[[7.4022, 9.2099, 0.3902, 9.6896],
 [9.2514, 4.4635, 6.6732, 1.0993],
]

Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: src.Size() == dst->Size() (4 vs. 0) : Cannot reshape array of size 4 into shape [2,0]
Stack trace:
  File "C:\source\mxnet-distro\mxnet-build\src\operator\numpy\np_matrix_op.cc", line 145

	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1788)
	at ai.djl.mxnet.jna.JnaUtils.imperativeInvoke(JnaUtils.java:500)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:82)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:66)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:329)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:347)
	at ai.djl.mxnet.engine.MxNDArray.reshape(MxNDArray.java:1167)
	at ai.djl.mxnet.engine.MxNDArray.set(MxNDArray.java:348)
	at ai.djl.ndarray.NDArray.set(NDArray.java:472)
	at Main.main(Main.java:11)
```

### Steps to reproduce
```
    public static void main(String[] args) {
        NDManager manager = NDManager.newBaseManager();
        NDArray array = manager.randomUniform(0, 10, new Shape(2, 4));
        System.out.println(array);
        array.set(new NDIndex(":, 2:"), arr -> arr.getNDArrayInternal().sigmoid());
        System.out.println(array);
    }
```

**Comment by lanking520** [comment]
I can reproduce your issue. https://github.com/awslabs/djl/blob/master/api/src/main/java/ai/djl/ndarray/index/NDIndex.java#L324. This is the pain point, I will make some fix there.

**Comment by lanking520** [comment]
@waicool20 Just fix with https://github.com/awslabs/djl/commit/23926642ceb60865f1b2a70335608fecb4797103.
Please checkout with snapshot build of API and verify

**Comment by waicool20** [comment]
Hmm I can confirm the test snippet above works on my side now, still doesn't work in my yolo model for some reason:
```
Exception in thread "main" ai.djl.engine.EngineException: MXNet engine call failed: MXNetError: Check failed: src.Size() == dst->Size() (1014 vs. 0) : Cannot reshape array of size 1014 into shape [507,0]
Stack trace:
  File "C:\source\mxnet-distro\mxnet-build\src\operator\numpy\np_matrix_op.cc", line 145

	at ai.djl.mxnet.jna.JnaUtils.checkCall(JnaUtils.java:1788)
	at ai.djl.mxnet.jna.JnaUtils.imperativeInvoke(JnaUtils.java:500)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:82)
	at ai.djl.mxnet.jna.FunctionInfo.invoke(FunctionInfo.java:66)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:321)
	at ai.djl.mxnet.engine.MxNDManager.invoke(MxNDManager.java:339)
	at ai.djl.mxnet.engine.MxNDArray.reshape(MxNDArray.java:1167)
	at ai.djl.mxnet.engine.MxNDArray.set(MxNDArray.java:348)
	at ai.djl.ndarray.NDArray.set(NDArray.java:472)
	at com.waicool20.djl.yolo.YoloTranslator.processOutput(YoloTranslator.kt:36)
	at com.waicool20.djl.yolo.YoloTranslator.processOutput(YoloTranslator.kt:13)
	at ai.djl.inference.Predictor.processOutputs(Predictor.java:202)
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:160)
	at ai.djl.inference.Predictor.predict(Predictor.java:112)
	at com.waicool20.djl.yolo.YoloRunKt.predictYolo(YoloRun.kt:86)
	at com.waicool20.djl.yolo.YoloRunKt.main(YoloRun.kt:59)
```

![image](https://user-images.githubusercontent.com/5538666/83529876-87406380-a51d-11ea-8afb-5927fba1bb74.png)

**Comment by waicool20** [comment]
I've deleted the gradle cache and let gradle redownload the dependencies and restarted IDEA and it works now. It's odd since the snippet above is in the same project so the dependencies should be the same... but at least it works now :+1:
