### ISSUE TITLE
How to train model on Android?

### ISSUE THREAD

**Issue by meteorlin** [awslabs/djl#830]
I implemented this [tutorial](https://github.com/awslabs/djl/blob/6ec9256c8deb104dff71250cec91aad5e0d968d7/jupyter/tutorial/02_train_your_first_model.ipynb) in Android Studio, but the program runs to `trainer.initialize(new Shape(1, 28 * 28));` error occurred. The error log is as follows:
```
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: ai.djl.engine.EngineException: Could not run 'aten::requires_grad_' with arguments from the 'CPU' backend. 'aten::requires_grad_' is only available for these backends: [BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: Named: fallthrough registered at ../aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: AutogradOther: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: AutogradCPU: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: AutogradCUDA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: AutogradXLA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: Tracer: fallthrough registered at ../torch/csrc/jit/frontend/tracer.cpp:967 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
2021-04-08 12:39:55.680 10999-11090/com.example.djlandroid W/System.err: VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.pytorch.jni.PyTorchLibrary.torchAttachGrad(Native Method)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.pytorch.jni.JniUtils.attachGradient(JniUtils.java:1332)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.pytorch.engine.PtNDArray.attachGradient(PtNDArray.java:170)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.nn.Parameter.initialize(Parameter.java:213)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:269)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.nn.SequentialBlock.initializeChildBlocks(SequentialBlock.java:143)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.nn.AbstractBlock.initialize(AbstractBlock.java:271)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at ai.djl.training.Trainer.initialize(Trainer.java:113)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at com.example.djlandroid.MainActivity.initModel(MainActivity.java:98)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at com.example.djlandroid.MainActivity.access$000(MainActivity.java:42)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at com.example.djlandroid.MainActivity$1.run(MainActivity.java:58)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid W/System.err:     at java.lang.Thread.run(Thread.java:919)
2021-04-08 12:39:55.681 10999-11090/com.example.djlandroid I/DJL-Error: Could not run 'aten::requires_grad_' with arguments from the 'CPU' backend. 'aten::requires_grad_' is only available for these backends: [BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
    
    BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
    Named: fallthrough registered at ../aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
    AutogradOther: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
    AutogradCPU: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
    AutogradCUDA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
    AutogradXLA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
    Tracer: fallthrough registered at ../torch/csrc/jit/frontend/tracer.cpp:967 [backend fallback]
    Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:254 [backend fallback]
    Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:511 [backend fallback]
    VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```
The dependencies of this project:
```
implementation "ai.djl:api:0.10.0"
implementation "ai.djl.android:core:0.10.0"
runtimeOnly "ai.djl.pytorch:pytorch-engine:0.10.0"
runtimeOnly "ai.djl.android:pytorch-native:0.10.0"

implementation "ai.djl:basicdataset:0.10.0"
implementation "ai.djl:model-zoo:0.10.0"
```
Is there any solution? Thanks in advance.

**Comment by stu1130** [comment]
Hi @meteorlin PyTorch doesn't support training on Android.

**Comment by meteorlin** [comment]
Thanks for your quick answer. Are there other frameworks to replace?

**Comment by lanking520** [comment]
Maybe you can take a look at here: https://github.com/alibaba/MNN. MNN support training on device

**Comment by meteorlin** [comment]
Thanks a lot!
